### ISSUE TITLE
How to run inference 

### ISSUE THREAD

**Issue by makaveli10** [TrojanXu/yolov5-tensorrt#1]
So, I tried converting onnx model to TRT using trtexec but that was not successful had some issues. Came across this work from you. I was curious to know if you had run any inference on the TRT engine generated through this repo. If yes please share the results or code if possible. THanks

**Comment by TrojanXu** [comment]
Yes, run the inference using main.py in this repo, you can get an exported onnx file. (using torch1.4.0+onnx1.6.0, this is important, otherwise, you might run into error with trtexec) With this onnx file, I think you can feed it to trtexec. But this onnx doesn't has nms now.

**Comment by makaveli10** [comment]
So, this repo is just for generating onnx model? I did not see any code regarding NMS in main.py is the inference running without NMS for now?

Also Do you plan on including NMS in the model itself? If that is possible?

**Comment by TrojanXu** [comment]
yes, inference is without nms for now, I plan to implement it as a separated engine.
The onnx model is generated and stored locally. Engine will be created in the script but not stored locally.

**Comment by makaveli10** [comment]
@TrojanXu Great thanks! Waiting for NMS to be implemented. Thanks
