### ISSUE TITLE
onnx file error

### ISSUE THREAD

**Issue by AITCK** [TrojanXu/yolov5-tensorrt#12]
ERROR: Failed to parse the ONNX file.
In node 0 (importModel): INVALID_GRAPH: Assertion failed: tensors.count(input_name)
Traceback (most recent call last):
  File "main.py", line 212, in <module>
    trt_result = profile_trt(build_engine(onnx_path, using_half), batch_size, 10, 100)
  File "main.py", line 118, in profile_trt
    assert(engine is not None)
AssertionError

**Comment by TrojanXu** [comment]
Looks like the exported onnx model is invalid. Do you get any other error information?

**Comment by pkraison** [comment]
> ERROR: Failed to parse the ONNX file.
> In node 0 (importModel): INVALID_GRAPH: Assertion failed: tensors.count(input_name)
> Traceback (most recent call last):
> File "main.py", line 212, in
> trt_result = profile_trt(build_engine(onnx_path, using_half), batch_size, 10, 100)
> File "main.py", line 118, in profile_trt
> assert(engine is not None)
> AssertionError
check whether you're using right yaml and weights

**Comment by AITCK** [comment]
@TrojanXu No other error information, maybe this is a version error of tensorrt, my tensorrt version is 6.0

**Comment by pkraison** [comment]
> @TrojanXu No other error information, maybe this is a version error of tensorrt, my tensorrt version is 6.0

Yes, I think you should upgrade it to 7/7+

**Comment by TrojanXu** [comment]
Yes, try 7/7+ please
