### ISSUE TITLE
reshape error  

### ISSUE THREAD

**Issue by pkraison** [TrojanXu/yolov5-tensorrt#13]
Traceback (most recent call last):
  File "main.py", line 212, in <module>
    trt_result = profile_trt(build_engine(onnx_path, using_half), batch_size, 10, 100)
  File "main.py", line 160, in profile_trt
    return [np.array(yolo_outputs[0].host.reshape(1, -1, 85))]
ValueError: cannot reshape array of size 123480 into shape (1,newaxis,85)
Segmentation fault (core dumped)

**Comment by TrojanXu** [comment]
https://github.com/TrojanXu/yolov5-tensorrt/issues/10 related to this one. I will push a new commit to fix this later. For now, please change 85 to nc+5.

**Comment by pkraison** [comment]
thanks!
