### ISSUE TITLE
tensorrt installation

### ISSUE THREAD

**Issue by 123456789mojtaba** [TrojanXu/yolov5-tensorrt#20]
how can I install tensorrt in pytorch in anaconda?

**Comment by TrojanXu** [comment]
tensorrt python binding is not part of PyTorch. If you have the tensorrt package, install from the python wheel from path_to_tensorrt_package/ptyhon/pyverxxx.whl. Otherwise, you can easily reproduce results with docker image pytorch:20.01-py3 from ngc.nvidia.com

**Comment by 123456789mojtaba** [comment]
can we convert yolov5  to tensorrt?
I read it has upsampling layer and leaky relu that have problem with
tensorrt?what  should we do?
plz help
