### ISSUE TITLE
writing trt engine to file fails deserialization: TensorRT] ERROR: INVALID_ARGUMENT: getPluginCreator could not find plugin BatchedNMS_TRT version 1

### ISSUE THREAD

**Issue by makaveli10** [TrojanXu/yolov5-tensorrt#22]
Added this code to the build_engine function:

    engine = builder.build_engine(network, config)
    print("Completed creating Engine")
    with open(engine_file, "wb") as f:
        f.write(engine.serialize())
        print(engine.serialize())
    return engine

which gives correct results for the first time when engine file is generated. But when reading from written engine file cannot find plugin, deserialization gives this error:

    [TensorRT] ERROR: INVALID_ARGUMENT: getPluginCreator could not find plugin BatchedNMS_TRT version 1
    [TensorRT] ERROR: safeDeserializationUtils.cpp (293) - Serialization Error in load: 0 (Cannot deserialize plugin since 
    corresponding IPluginCreator not found in Plugin Registry)
    [TensorRT] ERROR: INVALID_STATE: std::exception
    [TensorRT] ERROR: INVALID_CONFIG: Deserialize the cuda engine failed. 
    Traceback (most recent call last):
    File "main.py", line 379, in <module>
        trt_result = profile_trt(build_engine(onnx_path, using_half), batch_size, 10, 100)
    File "main.py", line 282, in profile_trt
        assert(engine is not None)
    AssertionError

**Comment by TrojanXu** [comment]
LD_PRELOAD=/path/to/libnvinfer_plugin.so python xxx, could this help?

**Comment by pkraison** [comment]
hey did you guys solve it?

**Comment by makaveli10** [comment]
@pkraison Since yolov5 is not working in deepstream so I did not move forward with @TrojanXu 's suggestion. You can try

**Comment by pkraison** [comment]
Okay, so you need to initialise the trt inference plugins. and the problem solved. I did it in build_engine function.

trt.init_libnvinfer_plugins(None, ' ')

**Comment by makaveli10** [comment]
@pkraison Great thanks! so the engine builds successfully and you are getting the correct output when reading from a prebuilt engine file?

**Comment by pkraison** [comment]
@makaveli10 yes, it's working!

**Comment by wangtianlong1994** [comment]
@makaveli10  Hello, may I ask what line is the code added to? Your build_engine function Can I see ？Thank you very much。
