### ISSUE TITLE
No module named 'tensorrt'

### ISSUE THREAD

**Issue by WestbrookZero** [TrojanXu/yolov5-tensorrt#29]
My environment is Win10，already install uff-0.6.5-py2.py3-none-any.whl and graphsurgeon-0.4.1-py2.py3-none-any.whl,but still have this error: 
Traceback (most recent call last):
  File "D:/Projects/DeepLearning/yolov5-tensorrt/main.py", line 8, in <module>
    import tensorrt as trt
ModuleNotFoundError: No module named 'tensorrt'

**Comment by TrojanXu** [comment]
You need to install tensorrt python wheel contained in downloaded tensorrt tar package.

**Comment by WestbrookZero** [comment]
there is no tensorrt whl in win10 package

**Comment by TrojanXu** [comment]
On windows, you might need WSL but with a lot of performance drop. Or just find a linux machine...
