### ISSUE TITLE
which ultralytics/yolov5 release is used

### ISSUE THREAD

**Issue by sudapure** [TrojanXu/yolov5-tensorrt#31]
Till this date , 2 versions has been released in ultralytics/yolov5 repo, 1.0 and 2.0 , so does the code in the repo point to specific release or it is pointing to active development branch only.

**Comment by TrojanXu** [comment]
yolov5 @ 37e13f8 it's a certain commit in dev branch. You can pull related commit via submodule update.

**Comment by TrojanXu** [comment]
The code now is updated to track v3.0 directly.
