### ISSUE TITLE
ERROR: Failed to parse the ONNX file.

### ISSUE THREAD

**Issue by makaveli10** [TrojanXu/yolov5-tensorrt#33]
This is the console output, it was working a like couple of weeks ago!! Now I am facing this error:
In node -1 (parseGraph): UNSUPPORTED_NODE: Assertion failed: convertOnnxWeights(initializer, &weights, ctx) 

                 from  n    params  module                                  arguments                     
      0             -1  1      3520  models.common.Focus                     [3, 32, 3]                    
      1             -1  1     18560  models.common.Conv                      [32, 64, 3, 2]                
      2             -1  1     19904  models.common.BottleneckCSP             [64, 64, 1]                   
      3             -1  1     73984  models.common.Conv                      [64, 128, 3, 2]               
      4             -1  1    161152  models.common.BottleneckCSP             [128, 128, 3]                 
      5             -1  1    295424  models.common.Conv                      [128, 256, 3, 2]              
      6             -1  1    641792  models.common.BottleneckCSP             [256, 256, 3]                 
      7             -1  1   1180672  models.common.Conv                      [256, 512, 3, 2]              
      8             -1  1    656896  models.common.SPP                       [512, 512, [5, 9, 13]]        
      9             -1  1   1248768  models.common.BottleneckCSP             [512, 512, 1, False]          
     10             -1  1    131584  models.common.Conv                      [512, 256, 1, 1]              
     11             -1  1         0  upsample.Upsample                       [None, 2, 'nearest']          
     12        [-1, 6]  1         0  models.common.Concat                    [1]                           
     13             -1  1    378624  models.common.BottleneckCSP             [512, 256, 1, False]          
     14             -1  1     33024  models.common.Conv                      [256, 128, 1, 1]              
     15             -1  1         0  upsample.Upsample                       [None, 2, 'nearest']          
     16        [-1, 4]  1         0  models.common.Concat                    [1]                           
     17             -1  1     95104  models.common.BottleneckCSP             [256, 128, 1, False]          
     18             -1  1     32895  torch.nn.modules.conv.Conv2d            [128, 255, 1, 1]              
     19             -2  1    147712  models.common.Conv                      [128, 128, 3, 2]              
     20       [-1, 14]  1         0  models.common.Concat                    [1]                           
     21             -1  1    313088  models.common.BottleneckCSP             [256, 256, 1, False]          
     22             -1  1     65535  torch.nn.modules.conv.Conv2d            [256, 255, 1, 1]              
     23             -2  1    590336  models.common.Conv                      [256, 256, 3, 2]              
     24       [-1, 10]  1         0  models.common.Concat                    [1]                           
     25             -1  1   1248768  models.common.BottleneckCSP             [512, 512, 1, False]          
     26             -1  1    130815  torch.nn.modules.conv.Conv2d            [512, 255, 1, 1]              
     27   [-1, 22, 18]  1         0  yolo.Detect                             [80, [[116, 90, 156, 198, 373, 326], [30, 61, 62, 45, 59, 119], [10, 13, 16, 30, 33, 23]]]
    Model Summary: 191 layers, 7.46816e+06 parameters, 7.46816e+06 gradients
    
    /usr/local/lib/python3.6/dist-packages/torch/serialization.py:593: SourceChangeWarning: source code of class 'models.yolo.Model' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
      warnings.warn(msg, SourceChangeWarning)
    /usr/local/lib/python3.6/dist-packages/torch/serialization.py:593: SourceChangeWarning: source code of class 'models.common.Conv' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
      warnings.warn(msg, SourceChangeWarning)
    /usr/local/lib/python3.6/dist-packages/torch/serialization.py:593: SourceChangeWarning: source code of class 'torch.nn.modules.conv.Conv2d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
      warnings.warn(msg, SourceChangeWarning)
    /usr/local/lib/python3.6/dist-packages/torch/serialization.py:593: SourceChangeWarning: source code of class 'torch.nn.modules.container.ModuleList' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
      warnings.warn(msg, SourceChangeWarning)
    [TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
    [TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
    [TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
    [TensorRT] WARNING: onnx2trt_utils.cpp:222: One or more weights outside the range of INT32 was clamped
    [TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
    [TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
    [TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
    [TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
    [TensorRT] WARNING: onnx2trt_utils.cpp:222: One or more weights outside the range of INT32 was clamped
    [TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
    [TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
    [TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
    [TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
    [TensorRT] WARNING: onnx2trt_utils.cpp:222: One or more weights outside the range of INT32 was clamped
    [TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
    [TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
    [TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
    [TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
    [TensorRT] WARNING: onnx2trt_utils.cpp:222: One or more weights outside the range of INT32 was clamped
    [TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
    [TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
    [TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
    [TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
    [TensorRT] WARNING: onnx2trt_utils.cpp:222: One or more weights outside the range of INT32 was clamped
    [TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
    [TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
    [TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
    [TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
    [TensorRT] WARNING: onnx2trt_utils.cpp:222: One or more weights outside the range of INT32 was clamped
    [TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
    [TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
    [TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
    [TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
    [TensorRT] WARNING: onnx2trt_utils.cpp:222: One or more weights outside the range of INT32 was clamped
    [TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
    [TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
    [TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
    [TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
    [TensorRT] WARNING: onnx2trt_utils.cpp:222: One or more weights outside the range of INT32 was clamped
    [TensorRT] WARNING: onnx2trt_utils.cpp:198: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
    ERROR: Failed to parse the ONNX file.
    In node -1 (parseGraph): UNSUPPORTED_NODE: Assertion failed: convertOnnxWeights(initializer, &weights, ctx)
    Traceback (most recent call last):
      File "main.py", line 378, in <module>
        trt_result = profile_trt(build_engine(onnx_path, using_half), batch_size, 10, 100)
      File "main.py", line 281, in profile_trt
        assert(engine is not None)
    AssertionError

**Comment by tensorflowt** [comment]
Hello! I met the same problem as you. How did you solve it ？
![74d5b1710e8a881d7b3af7dcfd3592a](https://user-images.githubusercontent.com/37217594/90389836-d594e580-e0bc-11ea-95fa-081abe1f3ea2.png)
