### ISSUE TITLE
cannot convert,help!!!

### ISSUE THREAD

**Issue by yushanshan05** [TrojanXu/yolov5-tensorrt#4]
I use pytorch（1.4.0），onnx（1.6.0），tensorrt（6.0）.
I can conver onnx form torch sucessful. But cant conver onnx to tensorrt.

These are the erros:
[TensorRT] ERROR: (Unnamed Layer* 0) [Slice]: slice is out of input range
ERROR: Failed to parse the ONNX file.
In node 9 (convert_axis): UNSUPPORTED_NODE: Assertion failed: axis >= 0 && axis < nbDims
Traceback (most recent call last):
  File "main.py", line 180, in <module>
    profile_trt(build_engine('yolov5_{}.onnx'.format(batch_size), using_half), batch_size)
  File "main.py", line 94, in profile_trt
    assert(engine is not None)
AssertionError

**Comment by TrojanXu** [comment]
Sorry I gave the wrong message in the initial commit. Please use pytorch1.4.0+onnx1.6.0+trt7.0 to see if this works.
