### ISSUE TITLE
how to build on Jetson Xavier?

### ISSUE THREAD

**Issue by batrlatom** [TrojanXu/yolov5-tensorrt#5]
Hi,
I tried it with Xavier ( aarch64) , but I am unable to install

onnx-simplify . 

How can I make it run on Jetson Xavier? 

Trying to go without simplifier got an error:

`  %549 : Tensor = onnx::Shape(%548)
  %550 : Tensor = onnx::Constant[value={0}]()
  %551 : Long() = onnx::Gather[axis=0](%549, %550) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:28:0
  %552 : Tensor = onnx::Shape(%548)
  %553 : Tensor = onnx::Constant[value={2}]()
  %554 : Long() = onnx::Gather[axis=0](%552, %553) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:28:0
  %555 : Tensor = onnx::Shape(%548)
  %556 : Tensor = onnx::Constant[value={3}]()
  %557 : Long() = onnx::Gather[axis=0](%555, %556) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:28:0
  %560 : Tensor = onnx::Unsqueeze[axes=[0]](%551)
  %563 : Tensor = onnx::Unsqueeze[axes=[0]](%554)
  %564 : Tensor = onnx::Unsqueeze[axes=[0]](%557)
  %565 : Tensor = onnx::Concat[axis=0](%560, %856, %857, %563, %564)
  %566 : Float(1, 3, 85, 80, 64) = onnx::Reshape(%548, %565) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:29:0
  %567 : Float(1, 3, 80, 64, 85) = onnx::Transpose[perm=[0, 1, 3, 4, 2]](%566) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:29:0
  %568 : Tensor = onnx::Unsqueeze[axes=[0]](%554)
  %569 : Tensor = onnx::ConstantOfShape[value={1}](%568)
  %570 : Tensor = onnx::NonZero(%569)
  %571 : Tensor = onnx::Transpose[perm=[1, 0]](%570)
  %572 : Tensor = onnx::Squeeze[axes=[1]](%571)
  %573 : Long(80) = onnx::Cast[to=7](%572) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:47:0
  %574 : Tensor = onnx::Unsqueeze[axes=[0]](%557)
  %575 : Tensor = onnx::ConstantOfShape[value={1}](%574)
  %576 : Tensor = onnx::NonZero(%575)
  %577 : Tensor = onnx::Transpose[perm=[1, 0]](%576)
  %578 : Tensor = onnx::Squeeze[axes=[1]](%577)
  %579 : Long(64) = onnx::Cast[to=7](%578) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:47:0
  %580 : Tensor = onnx::Constant[value={-1}]()
  %581 : Tensor = onnx::Reshape(%573, %580)
  %582 : Tensor = onnx::Constant[value={-1}]()
  %583 : Tensor = onnx::Reshape(%579, %582)
  %584 : Tensor = onnx::Shape(%581)
  %585 : Tensor = onnx::Shape(%583)
  %586 : Tensor = onnx::Concat[axis=0](%584, %585)
  %587 : Tensor = onnx::Constant[value={1}]()
  %588 : Tensor = onnx::Concat[axis=0](%584, %587)
  %589 : Tensor = onnx::Reshape(%581, %588)
  %590 : Tensor = onnx::Expand(%589, %586)
  %591 : Tensor = onnx::Constant[value={1}]()
  %592 : Tensor = onnx::Concat[axis=0](%591, %585)
  %593 : Tensor = onnx::Reshape(%583, %592)
  %594 : Tensor = onnx::Expand(%593, %586)
  %595 : Tensor = onnx::Unsqueeze[axes=[2]](%594)
  %596 : Tensor = onnx::Unsqueeze[axes=[2]](%590)
  %597 : Long(80, 64, 2) = onnx::Concat[axis=2](%595, %596) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:48:0
  %603 : Tensor = onnx::Unsqueeze[axes=[0]](%554)
  %604 : Tensor = onnx::Unsqueeze[axes=[0]](%557)
  %606 : Tensor = onnx::Concat[axis=0](%858, %859, %603, %604, %860)
  %607 : Long(1, 1, 80, 64, 2) = onnx::Reshape(%597, %606) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:48:0
  %608 : Float(1, 1, 80, 64, 2) = onnx::Cast[to=1](%607) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:48:0
  %609 : Float(1, 1, 80, 64, 2) = onnx::Cast[to=1](%608) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:33:0
  %610 : Float(1, 3, 80, 64, 85) = onnx::Sigmoid(%567) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:35:0
  %611 : Tensor = onnx::Constant[value={4}]()
  %612 : Tensor = onnx::Constant[value={0}]()
  %613 : Tensor = onnx::Constant[value={2}]()
  %614 : Tensor = onnx::Constant[value={1}]()
  %615 : Float(1, 3, 80, 64, 2) = onnx::Slice(%610, %612, %613, %611, %614) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:38:0
  %616 : Float() = onnx::Constant[value={2}]()
  %617 : Float(1, 3, 80, 64, 2) = onnx::Mul(%615, %616)
  %618 : Float() = onnx::Constant[value={0.5}]()
  %619 : Float(1, 3, 80, 64, 2) = onnx::Sub(%617, %618)
  %620 : Float(1, 1, 80, 64, 2) = onnx::Cast[to=1](%609) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:38:0
  %621 : Float(1, 3, 80, 64, 2) = onnx::Add(%619, %620) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:38:0
  %622 : Float() = onnx::Constant[value={8}]()
  %623 : Float(1, 3, 80, 64, 2) = onnx::Mul(%621, %622)
  %624 : Tensor = onnx::Constant[value={4}]()
  %625 : Tensor = onnx::Constant[value={2}]()
  %626 : Tensor = onnx::Constant[value={4}]()
  %627 : Tensor = onnx::Constant[value={1}]()
  %628 : Float(1, 3, 80, 64, 2) = onnx::Slice(%610, %625, %626, %624, %627) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:39:0
  %629 : Float() = onnx::Constant[value={2}]()
  %630 : Float(1, 3, 80, 64, 2) = onnx::Mul(%628, %629)
  %631 : Float() = onnx::Constant[value={2}]()
  %632 : Float(1, 3, 80, 64, 2) = onnx::Pow(%630, %631) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:39:0
  %633 : Tensor = onnx::Constant[value={0}]()
  %634 : Float(1, 3, 1, 1, 2) = onnx::Gather[axis=0](%model.22.anchor_grid, %633) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:39:0
  %635 : Float(1, 3, 80, 64, 2) = onnx::Mul(%632, %634) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:39:0
  %636 : Float(1, 3, 80, 64, 2) = onnx::Cast[to=1](%635) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:40:0
  %637 : Tensor = onnx::Constant[value={4}]()
  %638 : Tensor = onnx::Constant[value={4}]()
  %639 : Tensor = onnx::Constant[value={9223372036854775807}]()
  %640 : Tensor = onnx::Constant[value={1}]()
  %641 : Float(1, 3, 80, 64, 81) = onnx::Slice(%610, %638, %639, %637, %640) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:40:0
  %642 : Float(1, 3, 80, 64, 81) = onnx::Cast[to=1](%641) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:40:0
  %643 : Float(1, 3, 80, 64, 85) = onnx::Concat[axis=-1](%623, %636, %642) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:40:0
  %646 : Tensor = onnx::Unsqueeze[axes=[0]](%551)
  %649 : Tensor = onnx::Concat[axis=0](%646, %861, %862)
  %650 : Float(1, 15360, 85) = onnx::Reshape(%643, %649) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:41:0
  %651 : Tensor = onnx::Shape(%524)
  %652 : Tensor = onnx::Constant[value={0}]()
  %653 : Long() = onnx::Gather[axis=0](%651, %652) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:28:0
  %654 : Tensor = onnx::Shape(%524)
  %655 : Tensor = onnx::Constant[value={2}]()
  %656 : Long() = onnx::Gather[axis=0](%654, %655) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:28:0
  %657 : Tensor = onnx::Shape(%524)
  %658 : Tensor = onnx::Constant[value={3}]()
  %659 : Long() = onnx::Gather[axis=0](%657, %658) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:28:0
  %662 : Tensor = onnx::Unsqueeze[axes=[0]](%653)
  %665 : Tensor = onnx::Unsqueeze[axes=[0]](%656)
  %666 : Tensor = onnx::Unsqueeze[axes=[0]](%659)
  %667 : Tensor = onnx::Concat[axis=0](%662, %863, %864, %665, %666)
  %668 : Float(1, 3, 85, 40, 32) = onnx::Reshape(%524, %667) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:29:0
  %669 : Float(1, 3, 40, 32, 85) = onnx::Transpose[perm=[0, 1, 3, 4, 2]](%668) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:29:0
  %670 : Tensor = onnx::Unsqueeze[axes=[0]](%656)
  %671 : Tensor = onnx::ConstantOfShape[value={1}](%670)
  %672 : Tensor = onnx::NonZero(%671)
  %673 : Tensor = onnx::Transpose[perm=[1, 0]](%672)
  %674 : Tensor = onnx::Squeeze[axes=[1]](%673)
  %675 : Long(40) = onnx::Cast[to=7](%674) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:47:0
  %676 : Tensor = onnx::Unsqueeze[axes=[0]](%659)
  %677 : Tensor = onnx::ConstantOfShape[value={1}](%676)
  %678 : Tensor = onnx::NonZero(%677)
  %679 : Tensor = onnx::Transpose[perm=[1, 0]](%678)
  %680 : Tensor = onnx::Squeeze[axes=[1]](%679)
  %681 : Long(32) = onnx::Cast[to=7](%680) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:47:0
  %682 : Tensor = onnx::Constant[value={-1}]()
  %683 : Tensor = onnx::Reshape(%675, %682)
  %684 : Tensor = onnx::Constant[value={-1}]()
  %685 : Tensor = onnx::Reshape(%681, %684)
  %686 : Tensor = onnx::Shape(%683)
  %687 : Tensor = onnx::Shape(%685)
  %688 : Tensor = onnx::Concat[axis=0](%686, %687)
  %689 : Tensor = onnx::Constant[value={1}]()
  %690 : Tensor = onnx::Concat[axis=0](%686, %689)
  %691 : Tensor = onnx::Reshape(%683, %690)
  %692 : Tensor = onnx::Expand(%691, %688)
  %693 : Tensor = onnx::Constant[value={1}]()
  %694 : Tensor = onnx::Concat[axis=0](%693, %687)
  %695 : Tensor = onnx::Reshape(%685, %694)
  %696 : Tensor = onnx::Expand(%695, %688)
  %697 : Tensor = onnx::Unsqueeze[axes=[2]](%696)
  %698 : Tensor = onnx::Unsqueeze[axes=[2]](%692)
  %699 : Long(40, 32, 2) = onnx::Concat[axis=2](%697, %698) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:48:0
  %705 : Tensor = onnx::Unsqueeze[axes=[0]](%656)
  %706 : Tensor = onnx::Unsqueeze[axes=[0]](%659)
  %708 : Tensor = onnx::Concat[axis=0](%865, %866, %705, %706, %867)
  %709 : Long(1, 1, 40, 32, 2) = onnx::Reshape(%699, %708) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:48:0
  %710 : Float(1, 1, 40, 32, 2) = onnx::Cast[to=1](%709) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:48:0
  %711 : Float(1, 1, 40, 32, 2) = onnx::Cast[to=1](%710) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:33:0
  %712 : Float(1, 3, 40, 32, 85) = onnx::Sigmoid(%669) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:35:0
  %713 : Tensor = onnx::Constant[value={4}]()
  %714 : Tensor = onnx::Constant[value={0}]()
  %715 : Tensor = onnx::Constant[value={2}]()
  %716 : Tensor = onnx::Constant[value={1}]()
  %717 : Float(1, 3, 40, 32, 2) = onnx::Slice(%712, %714, %715, %713, %716) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:38:0
  %718 : Float() = onnx::Constant[value={2}]()
  %719 : Float(1, 3, 40, 32, 2) = onnx::Mul(%717, %718)
  %720 : Float() = onnx::Constant[value={0.5}]()
  %721 : Float(1, 3, 40, 32, 2) = onnx::Sub(%719, %720)
  %722 : Float(1, 1, 40, 32, 2) = onnx::Cast[to=1](%711) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:38:0
  %723 : Float(1, 3, 40, 32, 2) = onnx::Add(%721, %722) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:38:0
  %724 : Float() = onnx::Constant[value={16}]()
  %725 : Float(1, 3, 40, 32, 2) = onnx::Mul(%723, %724)
  %726 : Tensor = onnx::Constant[value={4}]()
  %727 : Tensor = onnx::Constant[value={2}]()
  %728 : Tensor = onnx::Constant[value={4}]()
  %729 : Tensor = onnx::Constant[value={1}]()
  %730 : Float(1, 3, 40, 32, 2) = onnx::Slice(%712, %727, %728, %726, %729) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:39:0
  %731 : Float() = onnx::Constant[value={2}]()
  %732 : Float(1, 3, 40, 32, 2) = onnx::Mul(%730, %731)
  %733 : Float() = onnx::Constant[value={2}]()
  %734 : Float(1, 3, 40, 32, 2) = onnx::Pow(%732, %733) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:39:0
  %735 : Tensor = onnx::Constant[value={1}]()
  %736 : Float(1, 3, 1, 1, 2) = onnx::Gather[axis=0](%model.22.anchor_grid, %735) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:39:0
  %737 : Float(1, 3, 40, 32, 2) = onnx::Mul(%734, %736) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:39:0
  %738 : Float(1, 3, 40, 32, 2) = onnx::Cast[to=1](%737) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:40:0
  %739 : Tensor = onnx::Constant[value={4}]()
  %740 : Tensor = onnx::Constant[value={4}]()
  %741 : Tensor = onnx::Constant[value={9223372036854775807}]()
  %742 : Tensor = onnx::Constant[value={1}]()
  %743 : Float(1, 3, 40, 32, 81) = onnx::Slice(%712, %740, %741, %739, %742) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:40:0
  %744 : Float(1, 3, 40, 32, 81) = onnx::Cast[to=1](%743) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:40:0
  %745 : Float(1, 3, 40, 32, 85) = onnx::Concat[axis=-1](%725, %738, %744) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:40:0
  %748 : Tensor = onnx::Unsqueeze[axes=[0]](%653)
  %751 : Tensor = onnx::Concat[axis=0](%748, %868, %869)
  %752 : Float(1, 3840, 85) = onnx::Reshape(%745, %751) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:41:0
  %753 : Tensor = onnx::Shape(%500)
  %754 : Tensor = onnx::Constant[value={0}]()
  %755 : Long() = onnx::Gather[axis=0](%753, %754) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:28:0
  %756 : Tensor = onnx::Shape(%500)
  %757 : Tensor = onnx::Constant[value={2}]()
  %758 : Long() = onnx::Gather[axis=0](%756, %757) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:28:0
  %759 : Tensor = onnx::Shape(%500)
  %760 : Tensor = onnx::Constant[value={3}]()
  %761 : Long() = onnx::Gather[axis=0](%759, %760) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:28:0
  %764 : Tensor = onnx::Unsqueeze[axes=[0]](%755)
  %767 : Tensor = onnx::Unsqueeze[axes=[0]](%758)
  %768 : Tensor = onnx::Unsqueeze[axes=[0]](%761)
  %769 : Tensor = onnx::Concat[axis=0](%764, %870, %871, %767, %768)
  %770 : Float(1, 3, 85, 20, 16) = onnx::Reshape(%500, %769) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:29:0
  %771 : Float(1, 3, 20, 16, 85) = onnx::Transpose[perm=[0, 1, 3, 4, 2]](%770) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:29:0
  %772 : Tensor = onnx::Unsqueeze[axes=[0]](%758)
  %773 : Tensor = onnx::ConstantOfShape[value={1}](%772)
  %774 : Tensor = onnx::NonZero(%773)
  %775 : Tensor = onnx::Transpose[perm=[1, 0]](%774)
  %776 : Tensor = onnx::Squeeze[axes=[1]](%775)
  %777 : Long(20) = onnx::Cast[to=7](%776) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:47:0
  %778 : Tensor = onnx::Unsqueeze[axes=[0]](%761)
  %779 : Tensor = onnx::ConstantOfShape[value={1}](%778)
  %780 : Tensor = onnx::NonZero(%779)
  %781 : Tensor = onnx::Transpose[perm=[1, 0]](%780)
  %782 : Tensor = onnx::Squeeze[axes=[1]](%781)
  %783 : Long(16) = onnx::Cast[to=7](%782) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:47:0
  %784 : Tensor = onnx::Constant[value={-1}]()
  %785 : Tensor = onnx::Reshape(%777, %784)
  %786 : Tensor = onnx::Constant[value={-1}]()
  %787 : Tensor = onnx::Reshape(%783, %786)
  %788 : Tensor = onnx::Shape(%785)
  %789 : Tensor = onnx::Shape(%787)
  %790 : Tensor = onnx::Concat[axis=0](%788, %789)
  %791 : Tensor = onnx::Constant[value={1}]()
  %792 : Tensor = onnx::Concat[axis=0](%788, %791)
  %793 : Tensor = onnx::Reshape(%785, %792)
  %794 : Tensor = onnx::Expand(%793, %790)
  %795 : Tensor = onnx::Constant[value={1}]()
  %796 : Tensor = onnx::Concat[axis=0](%795, %789)
  %797 : Tensor = onnx::Reshape(%787, %796)
  %798 : Tensor = onnx::Expand(%797, %790)
  %799 : Tensor = onnx::Unsqueeze[axes=[2]](%798)
  %800 : Tensor = onnx::Unsqueeze[axes=[2]](%794)
  %801 : Long(20, 16, 2) = onnx::Concat[axis=2](%799, %800) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:48:0
  %807 : Tensor = onnx::Unsqueeze[axes=[0]](%758)
  %808 : Tensor = onnx::Unsqueeze[axes=[0]](%761)
  %810 : Tensor = onnx::Concat[axis=0](%872, %873, %807, %808, %874)
  %811 : Long(1, 1, 20, 16, 2) = onnx::Reshape(%801, %810) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:48:0
  %812 : Float(1, 1, 20, 16, 2) = onnx::Cast[to=1](%811) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:48:0
  %813 : Float(1, 1, 20, 16, 2) = onnx::Cast[to=1](%812) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:33:0
  %814 : Float(1, 3, 20, 16, 85) = onnx::Sigmoid(%771) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:35:0
  %815 : Tensor = onnx::Constant[value={4}]()
  %816 : Tensor = onnx::Constant[value={0}]()
  %817 : Tensor = onnx::Constant[value={2}]()
  %818 : Tensor = onnx::Constant[value={1}]()
  %819 : Float(1, 3, 20, 16, 2) = onnx::Slice(%814, %816, %817, %815, %818) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:38:0
  %820 : Float() = onnx::Constant[value={2}]()
  %821 : Float(1, 3, 20, 16, 2) = onnx::Mul(%819, %820)
  %822 : Float() = onnx::Constant[value={0.5}]()
  %823 : Float(1, 3, 20, 16, 2) = onnx::Sub(%821, %822)
  %824 : Float(1, 1, 20, 16, 2) = onnx::Cast[to=1](%813) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:38:0
  %825 : Float(1, 3, 20, 16, 2) = onnx::Add(%823, %824) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:38:0
  %826 : Float() = onnx::Constant[value={32}]()
  %827 : Float(1, 3, 20, 16, 2) = onnx::Mul(%825, %826)
  %828 : Tensor = onnx::Constant[value={4}]()
  %829 : Tensor = onnx::Constant[value={2}]()
  %830 : Tensor = onnx::Constant[value={4}]()
  %831 : Tensor = onnx::Constant[value={1}]()
  %832 : Float(1, 3, 20, 16, 2) = onnx::Slice(%814, %829, %830, %828, %831) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:39:0
  %833 : Float() = onnx::Constant[value={2}]()
  %834 : Float(1, 3, 20, 16, 2) = onnx::Mul(%832, %833)
  %835 : Float() = onnx::Constant[value={2}]()
  %836 : Float(1, 3, 20, 16, 2) = onnx::Pow(%834, %835) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:39:0
  %837 : Tensor = onnx::Constant[value={2}]()
  %838 : Float(1, 3, 1, 1, 2) = onnx::Gather[axis=0](%model.22.anchor_grid, %837) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:39:0
  %839 : Float(1, 3, 20, 16, 2) = onnx::Mul(%836, %838) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:39:0
  %840 : Float(1, 3, 20, 16, 2) = onnx::Cast[to=1](%839) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:40:0
  %841 : Tensor = onnx::Constant[value={4}]()
  %842 : Tensor = onnx::Constant[value={4}]()
  %843 : Tensor = onnx::Constant[value={9223372036854775807}]()
  %844 : Tensor = onnx::Constant[value={1}]()
  %845 : Float(1, 3, 20, 16, 81) = onnx::Slice(%814, %842, %843, %841, %844) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:40:0
  %846 : Float(1, 3, 20, 16, 81) = onnx::Cast[to=1](%845) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:40:0
  %847 : Float(1, 3, 20, 16, 85) = onnx::Concat[axis=-1](%827, %840, %846) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:40:0
  %850 : Tensor = onnx::Unsqueeze[axes=[0]](%755)
  %853 : Tensor = onnx::Concat[axis=0](%850, %875, %876)
  %854 : Float(1, 960, 85) = onnx::Reshape(%847, %853) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:41:0
  %model/22 : Float(1, 20160, 85) = onnx::Concat[axis=1](%650, %752, %854) # /home/pekat/Devel/yolov5-tensorrt/yolo.py:43:0
  return (%model/22)

[TensorRT] WARNING: onnx2trt_utils.cpp:217: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:243: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: onnx2trt_utils.cpp:243: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: onnx2trt_utils.cpp:243: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: onnx2trt_utils.cpp:243: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: onnx2trt_utils.cpp:243: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: onnx2trt_utils.cpp:243: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: onnx2trt_utils.cpp:243: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: onnx2trt_utils.cpp:243: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: ModelImporter.cpp:135: No importer registered for op: NonZero. Attempting to import as plugin.
[TensorRT] ERROR: INVALID_ARGUMENT: getPluginCreator could not find plugin NonZero version 001
ERROR: Failed to parse the ONNX file.
In node -1 (importFallbackPluginImporter): UNSUPPORTED_NODE: Assertion failed: creator && "Plugin not found"
Traceback (most recent call last):
  File "main.py", line 212, in <module>
    trt_result = profile_trt(build_engine(onnx_path, using_half), batch_size, 10, 100)
  File "main.py", line 118, in profile_trt
    assert(engine is not None)
AssertionError
`

**Comment by TrojanXu** [comment]
I don't have jetson environment. I think you can run onnx-simpifier manually on a x86 server.

**Comment by batrlatom** [comment]
You mean like simplify model on x86 and then use this model on xavier. right? I am going to try. Thanks!

**Comment by batrlatom** [comment]
It works!!!! Thanks

**Comment by zhucheng725** [comment]
> It works!!!! Thanks

You can git clone https://github.com/daquexian/onnx-simplifier and python3 setup.py install after installing the onnxruntime and onnx. 

I have builded these on Jetson TX2

**Comment by rwin94** [comment]
@batrlatom what king of performance are you getting on jetson board if you dont mind me asking?
