### ISSUE TITLE
Build onnx for each image separately

### ISSUE THREAD

**Issue by makaveli10** [TrojanXu/yolov5-tensorrt#8]
I was trying to test on both the images but seems like by your method we need to export onnx for every image separately?

    def export_onnx(model, batch_size):
        _,_,x,y = input_img.shape
        img = torch.zeros((batch_size, 3, x, y)).to(device)
        torch.onnx.export(model, (img), 'yolov5_{}.onnx'.format(batch_size), 
               input_names=["data"], output_names=["model/22"], verbose=True, opset_version=10, operator_export_type=torch.onnx.OperatorExportTypes.ONNX
        )

Is that right?

**Comment by makaveli10** [comment]
How to run inference on multiple images. Currently, for the first image the output is correct but for the second image the output of first image is copied to the second.

**Comment by TrojanXu** [comment]
Refer to **limitation** section, dynamic shape is not working with current torch-onnx-trt combination, it ran into error when building the engine with dynamic shape. Currently, you can only use fixed input shape.
